# Stateful set
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: perseus
  name: litecoin
  labels: &labels
    app: litecoin
    version: 'v0.18.1'
spec:
  selector:
    matchLabels: *labels
  replicas: 1
  serviceName: litecoin-service
  template:
    metadata:
      labels: *labels
    spec:
      containers:
      - name: litecoin
        image: sourcecodemt/ltccore:1630461183
        imagePullPolicy: IfNotPresent
        readinessProbe:
          tcpSocket:
            port: 9333
        volumeMounts:
        - name: litecoin-config
          mountPath: "home/non-root/.litecoin"
        resources:
          requests:
            memory: 256Mi
          limits:
            cpu: 0.5
            memory: 256Mi
  volumeClaimTemplates:
  - metadata:
      name: litecoin-config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 15Gi
